export const sampleCampaigns = [
  {
    id: 1,
    name: "Tech Startups Q4 Outreach",
    nameAr: "حملة الشركات التقنية Q4",
    status: "active",
    temperature: "mixed",
    sequence: {
      steps: 5,
      schedule: [0, 3, 5, 7, 10],
    },
    targeting: {
      temperature: ["cold", "warm"],
      source: ["csv", "apollo"],
      industry: "Technology",
    },
    stats: {
      totalContacts: 234,
      sent: 1156,
      delivered: 1142,
      opened: 271,
      clicked: 48,
      replied: 8,
      bounced: 14,
      unsubscribed: 2,
      openRate: 23.4,
      clickRate: 4.2,
      replyRate: 0.7,
      deliverabilityRate: 98.8,
    },
    temperatureProgression: {
      cold: 12,
      warm: 18,
      hot: 8,
    },
    progress: {
      step1: 100,
      step2: 40,
      step3: 20,
      step4: 5,
      step5: 0,
    },
    createdAt: "2025-12-01",
    startedAt: "2025-12-05",
    lastActivity: "2025-12-16T03:00:00Z",
  },
  {
    id: 2,
    name: "Real Estate Agents - Dubai",
    nameAr: "وكلاء عقارات - دبي",
    status: "active",
    temperature: "warm",
    sequence: {
      steps: 4,
      schedule: [0, 3, 7, 14],
    },
    targeting: {
      temperature: ["warm"],
      source: ["instagram", "facebook"],
      location: "Dubai",
    },
    stats: {
      totalContacts: 156,
      sent: 468,
      delivered: 462,
      opened: 198,
      clicked: 32,
      replied: 12,
      bounced: 6,
      unsubscribed: 1,
      openRate: 42.3,
      clickRate: 6.9,
      replyRate: 2.6,
      deliverabilityRate: 98.7,
    },
    temperatureProgression: {
      cold: 0,
      warm: 45,
      hot: 12,
    },
    progress: {
      step1: 100,
      step2: 80,
      step3: 35,
      step4: 15,
    },
    createdAt: "2025-11-25",
    startedAt: "2025-11-28",
    lastActivity: "2025-12-16T02:30:00Z",
  },
  {
    id: 3,
    name: "E-commerce Follow-up",
    nameAr: "متابعة التجارة الإلكترونية",
    status: "paused",
    temperature: "hot",
    sequence: {
      steps: 3,
      schedule: [0, 2, 5],
    },
    targeting: {
      temperature: ["hot"],
      source: ["email_reply"],
      industry: "E-commerce",
    },
    stats: {
      totalContacts: 89,
      sent: 178,
      delivered: 176,
      opened: 145,
      clicked: 78,
      replied: 34,
      bounced: 2,
      unsubscribed: 0,
      openRate: 81.5,
      clickRate: 43.8,
      replyRate: 19.1,
      deliverabilityRate: 98.9,
    },
    temperatureProgression: {
      cold: 0,
      warm: 12,
      hot: 77,
    },
    progress: {
      step1: 100,
      step2: 95,
      step3: 78,
    },
    createdAt: "2025-12-10",
    startedAt: "2025-12-12",
    pausedAt: "2025-12-15",
    lastActivity: "2025-12-15T18:00:00Z",
  },
  {
    id: 4,
    name: "B2B SaaS Outreach",
    nameAr: "حملة SaaS للشركات",
    status: "active",
    temperature: "cold",
    sequence: {
      steps: 7,
      schedule: [0, 2, 4, 6, 9, 12, 16],
    },
    targeting: {
      temperature: ["cold"],
      source: ["hunter", "apollo"],
      industry: "Software",
    },
    stats: {
      totalContacts: 512,
      sent: 2048,
      delivered: 1986,
      opened: 318,
      clicked: 42,
      replied: 6,
      bounced: 62,
      unsubscribed: 8,
      openRate: 15.5,
      clickRate: 2.1,
      replyRate: 0.3,
      deliverabilityRate: 97.0,
    },
    temperatureProgression: {
      cold: 398,
      warm: 45,
      hot: 6,
    },
    progress: {
      step1: 100,
      step2: 85,
      step3: 65,
      step4: 42,
      step5: 28,
      step6: 15,
      step7: 5,
    },
    createdAt: "2025-12-08",
    startedAt: "2025-12-10",
    lastActivity: "2025-12-16T02:45:00Z",
  },
  {
    id: 5,
    name: "Instagram Engaged Leads",
    nameAr: "المتفاعلين على Instagram",
    status: "scheduled",
    temperature: "warm",
    sequence: {
      steps: 3,
      schedule: [0, 4, 8],
    },
    targeting: {
      temperature: ["warm"],
      source: ["instagram"],
      engagement: "commented",
    },
    stats: {
      totalContacts: 203,
      sent: 0,
      delivered: 0,
      opened: 0,
      clicked: 0,
      replied: 0,
      bounced: 0,
      unsubscribed: 0,
      openRate: 0,
      clickRate: 0,
      replyRate: 0,
      deliverabilityRate: 0,
    },
    temperatureProgression: {
      cold: 0,
      warm: 203,
      hot: 0,
    },
    progress: {
      step1: 0,
      step2: 0,
      step3: 0,
    },
    createdAt: "2025-12-15",
    scheduledFor: "2025-12-18T09:00:00Z",
    lastActivity: null,
  },
  {
    id: 6,
    name: "Re-engagement Campaign",
    nameAr: "حملة إعادة التفاعل",
    status: "completed",
    temperature: "cold",
    sequence: {
      steps: 2,
      schedule: [0, 7],
    },
    targeting: {
      temperature: ["frozen"],
      lastActivity: "30+ days ago",
    },
    stats: {
      totalContacts: 145,
      sent: 290,
      delivered: 286,
      opened: 23,
      clicked: 2,
      replied: 1,
      bounced: 4,
      unsubscribed: 6,
      openRate: 7.9,
      clickRate: 0.7,
      replyRate: 0.3,
      deliverabilityRate: 98.6,
    },
    temperatureProgression: {
      cold: 89,
      warm: 12,
      hot: 1,
    },
    progress: {
      step1: 100,
      step2: 100,
    },
    createdAt: "2025-11-20",
    startedAt: "2025-11-22",
    completedAt: "2025-12-05",
    lastActivity: "2025-12-05T15:00:00Z",
  },
]
